### ISSUE TITLE
Visual Studio doesn't clean up after itself...

### ISSUE THREAD

**Issue by StudioLE** [teamtreedyn/Binoculars#22]
If you run a `Debug` build in Visual Studio then run a `Release` build in Visual Studio then anything wrapped in an `#if DEBUG`  is still run even on the `Release` build.

I suspect what is happening is all `.dll` files in `bin` are copied to the Dynamo packages folder regardless of which build they refer to.

This is well beyond my knowledge so can somebody else weigh in/investigate? @2adicted @WaynePatrickDalton @radumg @brencass

https://github.com/teamtreedyn/Binoculars/blob/e0cf00e74b95c37f2ac07381bae780b42e9a1c58/Binoculars.csproj#L143-L172

Manually deleting the `bin` folder and the Dynamo `packages` folder seems to resolve the issue but shouldn't this be handled automatically?

**Comment by StudioLE** [comment]
Correction: Only deleting the Dynamo `packages` folder is necessary so I guess the following line isn't doing what it implies it should?

https://github.com/teamtreedyn/Binoculars/blob/e0cf00e74b95c37f2ac07381bae780b42e9a1c58/Binoculars.csproj#L168

**Comment by StudioLE** [comment]
I believe I've figured it out. The DeployFolder Condition in [Binoculars.csproj](https://github.com/teamtreedyn/Binoculars/blob/master/Binoculars.csproj) meant that Release builds were copied to `Dynamo\Dynamo Revit` when they should have been deployed to `Dynamo\Dynamo Core`

Should now be fixed in https://github.com/teamtreedyn/Binoculars/commit/1994fcd31d5800b705ba98a42e365d6d502103e7 pending review.

Before:
```xml
      <!--Copy to Dynamo sandbox for testing -->
      <DeployFolder Condition="'$(Configuration)' == 'Debug'">$(AppData)\Dynamo\Dynamo Core\2.0\packages\$(ProjectName)</DeployFolder>
      <!--Copy to Dynamo revit for publishing -->
      <DeployFolder Condition="'$(Configuration)' == 'Release' Or '$(Configuration)' == 'DebugRevit'">$(AppData)\Dynamo\Dynamo Revit\2.0\packages\$(ProjectName)</DeployFolder>
    
```
After:
```xml
      <!--Copy to Dynamo sandbox for testing -->
      <DeployFolder Condition="'$(Configuration)' == 'Debug' Or '$(Configuration)' == 'Release'">$(AppData)\Dynamo\Dynamo Core\2.0\packages\$(ProjectName)</DeployFolder>
      <!--Copy to Dynamo revit for publishing -->
      <DeployFolder Condition="'$(Configuration)' == 'DebugRevit'">$(AppData)\Dynamo\Dynamo Revit\2.0\packages\$(ProjectName)</DeployFolder>
```

**Comment by radumg** [comment]
> I believe I've figured it out. The DeployFolder Condition in [Binoculars.csproj](https://github.com/teamtreedyn/Binoculars/blob/master/Binoculars.csproj) meant that Release builds were copied to `Dynamo\Dynamo Revit` when they should have been deployed to `Dynamo\Dynamo Core`

This was the designed behaviour for the hackathon & training sessions, where we were using Sandbox, but also wanted to enable people to easily build for & deploy to Revit. Should have probably changed the name of that `Release` config though, so good fixing it !

**Comment by StudioLE** [comment]
> > I believe I've figured it out. The DeployFolder Condition in [Binoculars.csproj](https://github.com/teamtreedyn/Binoculars/blob/master/Binoculars.csproj) meant that Release builds were copied to `Dynamo\Dynamo Revit` when they should have been deployed to `Dynamo\Dynamo Core`
> 
> This was the designed behaviour for the hackathon & training sessions, where we were using Sandbox, but also wanted to enable people to easily build for & deploy to Revit. Should have probably changed the name of that `Release` config though, so good fixing it !

Yes, it makes sense. I just made the assumption that `Release`  followed the same principles as `Debug`  and `DebugRevit` would therefore have a similarly suffixed `ReleaseRevit`.
